#!/usr/bin/env python3
"""Launch a tmux-visible Rally agentic production run."""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .roles import ROLE_SPECS
from .studio import ALL_GATES, build_run_payload, gate_template


BASE = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE.parent
RUNS_DIR = BASE / "runs"


def main() -> None:
    parser = argparse.ArgumentParser(description="Launch Rally production agents in tmux")
    parser.add_argument("--project", required=True, help="Project id, e.g. openscreen")
    parser.add_argument("--style", required=True, help="Style card id")
    parser.add_argument("--run-id", help="Stable run id. Defaults to project_style_timestamp")
    parser.add_argument("--goal", default="Produce one high-quality short-form video candidate.", help="Run goal")
    parser.add_argument("--layout", choices=("windows", "panes"), default="windows", help="Tmux layout")
    parser.add_argument("--attach", action="store_true", help="Attach after launch")
    parser.add_argument("--dry-run", action="store_true", help="Create run files and print tmux commands only")
    args = parser.parse_args()

    run_id = _safe_run_id(args.run_id or _default_run_id(args.project, args.style))
    run_dir = RUNS_DIR / run_id
    session = _safe_session_name(f"rally-{run_id}")

    _ensure_tmux_available()
    _init_run_dir(run_dir, run_id, args.project, args.style, args.goal, session)

    commands = _build_tmux_commands(
        session=session,
        run_dir=run_dir,
        layout=args.layout,
    )

    if args.dry_run:
        print(f"Run dir: {run_dir}")
        print(f"Session: {session}")
        for cmd in commands:
            print(" ".join(cmd))
        return

    if _session_exists(session):
        raise SystemExit(
            f"tmux session already exists: {session}\n"
            f"Attach with: tmux attach -t {session}\n"
            "Use a different --run-id for a new session."
        )

    for cmd in commands:
        subprocess.run(cmd, check=True, cwd=BASE)

    print(f"Launched tmux session: {session}")
    print(f"Run dir: {run_dir}")
    print(f"Attach: tmux attach -t {session}")
    if args.attach:
        os.execvp("tmux", ["tmux", "attach", "-t", session])


def _ensure_tmux_available() -> None:
    result = subprocess.run(["tmux", "-V"], capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit("tmux is not available on PATH")


def _init_run_dir(
    run_dir: Path,
    run_id: str,
    project: str,
    style_id: str,
    goal: str,
    session: str,
) -> None:
    for path in (
        run_dir,
        run_dir / "artifacts",
        run_dir / "assets",
        run_dir / "blockers",
        run_dir / "final",
        run_dir / "gates",
        run_dir / "handoffs",
        run_dir / "logs",
        run_dir / "memory",
        run_dir / "prompts",
        run_dir / "status",
    ):
        path.mkdir(parents=True, exist_ok=True)

    run_path = run_dir / "run.json"
    if not run_path.exists():
        payload = build_run_payload(
            run_id=run_id,
            project=project,
            style_id=style_id,
            goal=goal,
            session=session,
            repo_root=REPO_ROOT,
            poc_root=BASE,
            roles=[spec.role for spec in ROLE_SPECS],
        )
        run_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    _init_gates(run_dir)
    _init_readme(run_dir, session)


def _init_gates(run_dir: Path) -> None:
    for gate in ALL_GATES:
        path = run_dir / "gates" / f"{gate}.json"
        if path.exists():
            continue
        path.write_text(json.dumps(gate_template(gate), indent=2), encoding="utf-8")


def _init_readme(run_dir: Path, session: str) -> None:
    path = run_dir / "README.md"
    if path.exists():
        return
    path.write_text(f"""# Rally Agentic Run

Attach:

```bash
tmux attach -t {session}
```

Important directories:

- `prompts/`: role prompts generated by the launcher.
- `handoffs/`: visible handoff notes for each role.
- `artifacts/`: outputs owned by roles.
- `gates/`: quality gates.
- `status/`: heartbeat/status per role.
- `assets/`: generated media assets.
- `final/`: rough and final cuts.
- `blockers/`: structured blockers when a role cannot proceed.
- `memory/`: review and retry events for future autonomy.

If `RALLY_AGENT_COMMAND_TEMPLATE` was not set before launch, panes run in
scaffold mode and wait visibly for an operator or a later model runner.

Minimal operator commands:

```bash
python3 -m agents.cli status --run-dir {run_dir}
python3 -m agents.cli approve-gate --run-dir {run_dir} --gate concept --decision approve --actor "$USER" --notes "approved"
python3 -m agents.cli retry-shot --run-dir {run_dir} --shot s01 --reason "weak hook" --suggested-fix "stronger first frame"
```
""", encoding="utf-8")


def _build_tmux_commands(session: str, run_dir: Path, layout: str) -> list[list[str]]:
    if layout == "panes":
        return _build_pane_commands(session, run_dir)
    return _build_window_commands(session, run_dir)


def _build_window_commands(session: str, run_dir: Path) -> list[list[str]]:
    commands: list[list[str]] = []
    first = ROLE_SPECS[0]
    commands.append([
        "tmux", "new-session", "-d",
        "-s", session,
        "-n", first.pane_name,
        "-c", str(BASE),
        _worker_command(run_dir, first.role),
    ])
    for spec in ROLE_SPECS[1:]:
        commands.append([
            "tmux", "new-window",
            "-t", session,
            "-n", spec.pane_name,
            "-c", str(BASE),
            _worker_command(run_dir, spec.role),
        ])
    commands.append(["tmux", "select-window", "-t", f"{session}:0"])
    return commands


def _build_pane_commands(session: str, run_dir: Path) -> list[list[str]]:
    commands: list[list[str]] = []
    first = ROLE_SPECS[0]
    commands.append([
        "tmux", "new-session", "-d",
        "-s", session,
        "-n", "agents",
        "-c", str(BASE),
        _worker_command(run_dir, first.role),
    ])
    for idx, spec in enumerate(ROLE_SPECS[1:], start=1):
        split_flag = "-h" if idx % 2 else "-v"
        commands.append([
            "tmux", "split-window",
            split_flag,
            "-t", session,
            "-c", str(BASE),
            _worker_command(run_dir, spec.role),
        ])
        commands.append(["tmux", "select-layout", "-t", session, "tiled"])
    return commands


def _worker_command(run_dir: Path, role: str) -> str:
    return f"python3 -m agents.worker --run-dir {run_dir} --role {role}"


def _session_exists(session: str) -> bool:
    result = subprocess.run(["tmux", "has-session", "-t", session], capture_output=True)
    return result.returncode == 0


def _default_run_id(project: str, style: str) -> str:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{project}_{style}_{stamp}"


def _safe_run_id(value: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    return clean.strip("._-") or "rally_run"


def _safe_session_name(value: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    return clean[:80].strip("._-") or "rally"


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        print(f"Command failed: {exc}", file=sys.stderr)
        raise SystemExit(exc.returncode) from exc
